vim.keymap.set("n", "-", "<cmd>Oil --float<CR>", { desc = "Open Parent Directory in Oil" })
vim.keymap.set("n", "gl", function()
    vim.diagnostic.open_float()
end, { desc = "Open Diagnostics in Float" })
vim.keymap.set("n", "<leader>cf", function()
    require("conform").format({
        lsp_format = "fallback",
    })
end, { desc = "Format current file" })

vim.keymap.set("n", "<leader>ea", function()
    vim.cmd("argadd %")
    vim.cmd("argdedup")
end)
vim.keymap.set("n", "<leader>el", function()
    vim.cmd.args()
end)
vim.keymap.set("n", "<C-h>", function()
    vim.cmd("silent! 1argument")
end)
vim.keymap.set("n", "<C-j>", function()
    vim.cmd("silent! 2argument")
end)
vim.keymap.set("n", "<C-k>", function()
    vim.cmd("silent! 3argument")
end)
vim.keymap.set("n", "<C-l>", function()
    vim.cmd("silent! 4argument")
end)
